//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurantes
    {
        public Restaurantes()
        {
            this.Categorias = new HashSet<Categorias>();
            this.Reservas = new HashSet<Reservas>();
            this.Servicios = new HashSet<Servicios>();
        }
    
        public int nit { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string slogan { get; set; }
        public decimal puntuacion { get; set; }
        public Nullable<short> tenedor { get; set; }
        public System.DateTime fecha { get; set; }
        public int user_cedula { get; set; }
    
        public virtual ICollection<Categorias> Categorias { get; set; }
        public virtual Imegenes Imegenes { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual ICollection<Servicios> Servicios { get; set; }
        public virtual User User { get; set; }
    }
}
